### ISSUE TITLE
Averaging periods in the TS-plot

### ISSUE THREAD

**Issue by steingod** [epifanio/pybasket_services#1]
In the TS-plot there is an opportunity to visualisedifferent freqencies of the data. I assume this is merely plotting selected points according to All, Hourly, Daily, Weekly, Monthly, Quarterly and Yearly, abbreviated as --, H, D, W, M, Q, Y. It would be good to have some more guidance on this e.g. indicating that no averaging (or if) is done and also to spell out the specifications in full in the drop down menu. The current version is overly compact for non expert users.

**Comment by epifanio** [comment]
it  uses a [resampling mechanism](https://pandas.pydata.org/docs/reference/api/pandas.Series.resample.html) built into pandas - - see here [Frequency String](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects) for details about the frequency used to resample the dataset.

I agree the drop down menu needs the full string for a better user experience.

**Comment by steingod** [comment]
Concerning the pandas mechanism I think just a brief statement explaining that it isn't an averaging process would be good from a user perspective. Using the phrase resampling is actually quite good, but perhaps also explicitly stating no averaging...

**Comment by epifanio** [comment]
This is now implemented on the service we have in production - I am using the following mapping dictionary:

```python
        pandas_frequency_offsets = {
            "Hourly": "H",
            "Calendar day": "D",
            "Weekly": "W",
            "Month end": "M",
            "Quarter end": "Q",
            "Yearly": "Y",
        }
```

- `key`: text-label used in the UI
- `value`: corresponding pandas frequency string

**Comment by steingod** [comment]
Perfect
